# Generated by Django 4.2.7 on 2023-11-25 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('book_title', models.CharField(max_length=225)),
                ('author', models.CharField(blank=True, max_length=225, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_year', models.IntegerField()),
                ('edition', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
