# Generated by Django 4.2.7 on 2023-11-25 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
