# Generated by Django 4.2.7 on 2023-11-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0003_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='staic/pdf/')),
                ('book_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookapi.book')),
            ],
        ),
    ]
