# Generated by Django 4.2.7 on 2023-11-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0004_bookmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedia',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
